//GET
###
//Returns a list with all users
GET http://localhost:3000/user



//POST

###
//Create a new user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Miquel",
    "surname":"Abella Gustà",
    "age":"37",
    "birthdate":"1986-05-29",
    "image":"",
    "phone":"670320596",
    "email":"miquel.abella.dw@immune.institute",
    "password":"You&me261202"
}
