//GET
###
//Returns a list with all users
GET http://localhost:3000/user

###
//Return the user with the id specified in the url

GET http://localhost:3000/user/5

//POST

###
//Create a new user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Juan",
    "surname":"",
    "age":"23",
    "birthdate":"1986-04-23",
    "image":"",
    "phone":"",
    "email":"",
    "password":""
}

###
//login

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"",
    "password":""
}

//PUT

###
//update an existing user (the userId must be specified in the url)

PUT http://localhost:3000/user/5
Content-Type: application/json

{
    "name": "",
    "surname":"",
    "age":"",
    "birthdate":"",
    "image":"",
    "phone":"",
    "email":"",
    "password":""

}

//DELETE

###
DELETE http://localhost:3000/user/6